### ISSUE TITLE
Next build not works

### ISSUE THREAD

**Issue by bezzskilla** [hufan-akari/seamless-scroll-polyfill#131] opened 2022-02-17 11:21 UTC
i was using old your API for a long time. Now i decided to upd it to `2.1.6`. So I rewrite method `windowScrollTo`

My code:
`import { windowScrollTo } from 'seamless-scroll-polyfill';`

`<div onClick={handleScroll} className={className}>
      {children}
    </div>`
and `handleScroll` is calculating offsetPosition and scroll in the end:
`window &&
        windowScrollTo(window, {
          top: offsetPosition,
          behavior: "smooth",
        });`
        
All is perfect when i check `next dev` in Next.js, but it not works, when I use `next build`
I tryied another methods like `windowScroll` or do it in `try-catch` or check `isWindow` but without success

**Comment by magic-akari** [comment] 2022-02-17 11:52
Thank you for your feedback.
Can you provide a minimal reproduction to help me locate the issue?

**Comment by bezzskilla** [comment] 2022-02-17 12:08
yep, some time

**Comment by bezzskilla** [comment] 2022-02-17 12:27
https://codesandbox.io/embed/next-js-forked-77c1t0?fontsize=14&hidenavigation=1&theme=dark

code like this but u shold do `next build` and `next start` for my case. I think sandbox couldnt do it

**Comment by magic-akari** [comment] 2022-02-17 14:19
Are you using the `next@3`?

**Comment by magic-akari** [comment] 2022-02-17 16:04
Test on `next@12` and everything is OK.
So the issue may be that `next@3` can not select `esm`/`cjs` correctly.

[nextjs-blog.zip](https://github.com/magic-akari/seamless-scroll-polyfill/files/8090191/nextjs-blog.zip)

**Comment by bezzskilla** [comment] 2022-02-17 16:13
i use next 11

**Comment by magic-akari** [comment] 2022-02-17 16:48
`seamless-scroll-polyfill@2.1.6` works well on both `next@11` and `next@12`.
There are some compatibility issues in `next@10`. I have just released 2.1.7 to improve compatibility.
I test it from `next@8` to `next@12`, it works well.
For versions below `next@8`, I couldn't continue testing because of some compatibility issues between `React` and `next`.

**Comment by magic-akari** [comment] 2022-02-17 16:55
Since you are using next 11 so you may be experiencing a different issue.
But it's still worth trying to upgrade to 2.1.7.

**Comment by bezzskilla** [comment] 2022-02-18 08:14
so, i locally created next app. On last version all is okey. But on `next 11.1.3 `its not working. I can give u repository with code if u want. 
i was using scroll `2.1.7`
I also understand that this is not the latest version, so it may not be rational to fix something on it, I just inform you

**Comment by bezzskilla** [comment] 2022-02-18 08:28
By the way 11.1.3 is the latest version of 11 next

**Comment by magic-akari** [comment] 2022-02-18 08:30
Does the 2.1.7 version works on `next@11.1.3` ?

**Comment by bezzskilla** [comment] 2022-02-18 08:45
no, check it pls
`https://github.com/bezzskilla/scroll-bug`

dev - works
build + start - not works

scroll api - 2.1.7
next - 11.1.3

**Comment by magic-akari** [comment] 2022-02-18 08:57
Thanks, it helps a lot.
I will check it out in depth.

**Comment by magic-akari** [comment] 2022-02-19 12:09
The webpack in  `next@11` cannot handle `??` logic correctly.
The following code will be inlined and transformed into wrong result.

https://github.com/magic-akari/seamless-scroll-polyfill/blob/8c0841374ba6b824024486a357141878ab844276/src/scroll.ts#L21-L28

This issue will be bypassed in these cases.
- disable webpack minimizer in `next.config.js` by `config.optimization.minimizer = []`
- use latest terser as webpack minimizer
- use latest `next.js`
- use `seamless-scroll-polyfill@2.1.8`

I just released 2.1.8. which downgraded the build target to es6.

**Comment by bezzskilla** [comment] 2022-02-19 12:30
nice! thx, i'll check it in the evening

**Comment by bezzskilla** [comment] 2022-02-21 09:00
thx again, all works perfect!

**Closed as completed** 2022-02-21 09:00 UTC
